### ISSUE TITLE
Create an MVP scope and update the roadmap with the initial set of features

### ISSUE THREAD

**Issue by mluky193** [VIN-Data-Products/vdp-specification#1]
### Checklist
- [x] Create MVP (Phase 0) page in documentation
- [x] Populate the page with information from the Customer
- [x] Create issues/milestones for related repos
- [x] Make sure that new tasks are reflected on the [Project Page](https://github.com/orgs/VIN-Data-Products/projects/1)

**Comment by mluky193** [comment]
Top 5 issues has been created for Admin part only. Other issues to be created by @mmaximov-tc in appropriate repositories

cc: @AliakseiVihuro
